import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';
import { Providers } from './prodiders';
import PageAnimatePresence from '@/components/PageAnimatePresence';

const monserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-mont',
});

export const metadata: Metadata = {
  title: "Yasen's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${monserrat.variable} font-mont bg-light dark:bg-dark w-full min-h-screen`}
      >
        <Providers>
          <NavBar />
          <PageAnimatePresence>{children}</PageAnimatePresence>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
